// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrivateLessons.Infrastructure.Data;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(PrivateLessonsDbContext))]
    [Migration("20260614141039_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrivateLessons.Domain.Entities.Cas", b =>
                {
                    b.Property<int>("CasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CasId"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("PredavacId")
                        .HasColumnType("int");

                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UcenikId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("VremePocetka")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("VremeZavrsetka")
                        .HasColumnType("time");

                    b.HasKey("CasId");

                    b.HasIndex("PredavacId");

                    b.HasIndex("PredmetId");

                    b.HasIndex("UcenikId");

                    b.ToTable("Casovi");
                });

            modelBuilder.Entity("PrivateLessons.Domain.Entities.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikId"));

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipKorisnika")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("KorisnikId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Korisnik");

                    b.HasDiscriminator<string>("TipKorisnika").HasValue("Korisnik");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PrivateLessons.Domain.Entities.Predaje", b =>
                {
                    b.Property<int>("PredavacId")
                        .HasColumnType("int");

                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.Property<int>("GodineIskustva")
                        .HasColumnType("int");

                    b.Property<int>("Nivo")
                        .HasColumnType("int");

                    b.HasKey("PredavacId", "PredmetId");

                    b.HasIndex("PredmetId");

                    b.ToTable("Predaje");
                });

            modelBuilder.Entity("PrivateLessons.Domain.Entities.Predmet", b =>
                {
                    b.Property<int>("PredmetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PredmetId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Oblast")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PredmetId");

                    b.ToTable("Predmeti");
                });

            modelBuilder.Entity("PrivateLessons.Domain.Entities.Predavac", b =>
                {
                    b.HasBaseType("PrivateLessons.Domain.Entities.Korisnik");

                    b.Property<string>("Biografija")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("CenaPoSatu")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("PREDAVAC");
                });

            modelBuilder.Entity("PrivateLessons.Domain.Entities.Ucenik", b =>
                {
                    b.HasBaseType("PrivateLessons.Domain.Entities.Korisnik");

                    b.Property<string>("Razred")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Skola")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasDiscriminator().HasValue("UCENIK");
                });

            modelBuilder.Entity("PrivateLessons.Domain.Entities.Cas", b =>
                {
                    b.HasOne("PrivateLessons.Domain.Entities.Predavac", "Predavac")
                        .WithMany("Casovi")
                        .HasForeignKey("PredavacId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrivateLessons.Domain.Entities.Predmet", "Predmet")
                        .WithMany("Casovi")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrivateLessons.Domain.Entities.Ucenik", "Ucenik")
                        .WithMany("Casovi")
                        .HasForeignKey("UcenikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Predavac");

                    b.Navigation("Predmet");

                    b.Navigation("Ucenik");
                });

            modelBuilder.Entity("PrivateLessons.Domain.Entities.Predaje", b =>
                {
                    b.HasOne("PrivateLessons.Domain.Entities.Predavac", "Predavac")
                        .WithMany("PredajePredmete")
                        .HasForeignKey("PredavacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrivateLessons.Domain.Entities.Predmet", "Predmet")
                        .WithMany("Predavaci")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predavac");

                    b.Navigation("Predmet");
                });

            modelBuilder.Entity("PrivateLessons.Domain.Entities.Predmet", b =>
                {
                    b.Navigation("Casovi");

                    b.Navigation("Predavaci");
                });

            modelBuilder.Entity("PrivateLessons.Domain.Entities.Predavac", b =>
                {
                    b.Navigation("Casovi");

                    b.Navigation("PredajePredmete");
                });

            modelBuilder.Entity("PrivateLessons.Domain.Entities.Ucenik", b =>
                {
                    b.Navigation("Casovi");
                });
#pragma warning restore 612, 618
        }
    }
}
